name: palm_reading_chatbot_proto
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  camera_camera: any
  provider: ^6.0.5
  video_player: ^2.4.10
  flutter_spinkit: ^5.1.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/subCat/heartLine/heart1.png
    - images/subCat/heartLine/heart2.png
    - images/subCat/heartLine/heart3.png
    - images/subCat/heartLine/heart4.png
    - images/subCat/heartLine/heart4.png
    - images/subCat/heartLine/heart5.png
    - images/subCat/heartLine/heart6.png
    - images/subCat/heartLine/heart7.png

    - images/subCat/marriageLine/marriage1.png
    - images/subCat/marriageLine/marriage2.png
    - images/subCat/marriageLine/marriage3.png
    - images/subCat/marriageLine/marriage4.png
    - images/subCat/marriageLine/marriage5.png
    - images/subCat/marriageLine/marriage6.png
    - images/subCat/marriageLine/marriage7.png
    - images/subCat/marriageLine/marriage8.png
    - images/subCat/marriageLine/marriage9.png
    - images/subCat/marriageLine/marriage10.png
    - images/subCat/marriageLine/marriage11.png
    - images/subCat/marriageLine/marriage12.png

    - images/subCat/lifeLine/life1.png
    - images/subCat/lifeLine/life2.png
    - images/subCat/lifeLine/life3.png
    - images/subCat/lifeLine/life4.png

    - images/subCat/travelLine/travel1.png
    - images/subCat/travelLine/travel2.png
    - images/subCat/travelLine/travel3.png
    - images/subCat/travelLine/travel4.png
    - images/subCat/travelLine/travel5.png

    - images/subCat/headLine/head1.png
    - images/subCat/headLine/head2.png
    - images/subCat/headLine/head3.png
    - images/subCat/headLine/head4.png
    - images/subCat/headLine/head5.png
    - images/subCat/headLine/head6.png
    - images/subCat/headLine/head7.png
    - images/subCat/headLine/head8.png
    - images/subCat/headLine/head9.png
    - images/subCat/headLine/head10.png

    - images/subCat/successLine/success1.png
    - images/subCat/successLine/success2.png
    - images/subCat/successLine/success3.png
    - images/subCat/successLine/success4.png
    - images/subCat/successLine/success5.png
    - images/subCat/successLine/success6.png
    - images/subCat/successLine/success7.png
    - images/subCat/successLine/success8.png

    - images/subCat/fateLine/fate1.png
    - images/subCat/fateLine/fate2.png
    - images/subCat/fateLine/fate3.png
    - images/subCat/fateLine/fate4.png
    - images/subCat/fateLine/fate5.png
    - images/subCat/fateLine/fate1.png
    - images/subCat/fateLine/fate2.png
    - images/subCat/fateLine/fate3.png
    - images/subCat/fateLine/fate4.png
    - images/subCat/fateLine/fate5.png
    - images/subCat/fateLine/fate6.png
    - images/subCat/fateLine/fate7.png
    - images/subCat/fateLine/fate8.png
    - images/subCat/fateLine/fate9.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
